#import "lib.typ": *

#deftable(
  ([#C#D#H#S#N], [clubs, diamonds, hearts, spades, notrump]),
  ([#dbl], [double]),
  ([#rdbl], [redouble]),
  ([$X$/$Y$/$Z$], [unspecified suit that does not change in a bidtable]),
  ([#M], [major]),
  ([#m], [minor]),
  ([#MM], [both majors]),
  ([#mm], [both minors]),
  ([oM], [other major]),
  ([om], [other minor]),
  ([nat], [natural]),
  ([BAL], [balanced]),
  ([unBAL], [unbalanced]),
  ([(xyzw)], [fluid distribution]),
  ([xyzw], [exact distribution]),
  ([PRE], [preempitve]),
  ([NF], [non-forcing]),
  ([F1], [forcing for 1 round]),
  ([INV], [exactly invitational]),
  ([INV#plus], [at least invitational]),
  ([FX], [forcing until X]),
  ([GF], [game force]),
  ([SI], [slam interest]),
  ([ST], [slam try]),
  ([P/C], [pass or correct]),
  ([LMH], [low, middle, high]),
  ([flag], [sets suit as a trump]),
  ([R], [relay/next bid]),
  ([RKC], [Roman Keycard Blackwood]),
  ([KRKC], [Kickback Roman Keycard Blackwood]),
  ([XYZ], [convention after 1$X$ (not #C)---1$Y$---1$Z$ sequence]),
  ([COG], [choice of games]),
  ([NV], [non-vulnerable]),
  ([VUL], [vulnerable]),
  ([MIN], [minimum]),
  ([MAX], [maximum]),
)
